### ISSUE TITLE
auto confirm  flag doesn't work when running npm init

### ISSUE THREAD

**Issue by Xesenix** [npm/init-package-json#108]
# What / Why
Autoconfirm mode doesn't work when running
```
npm init package-json -y
```

### Current Behavior
```
npm init package-json -y
```
Asks for each configuration option instead of auto confirming defaults.

### Expected Behavior
There should not be any console input requests.

**Comment by nlf** [comment]
`npm init package-json` is downloading and running the package `create-package-json`, the `-y` option passed to `npm init` is being ignored because it's no longer `npm` responsible for monitoring it, rather it's the `create-package-json` package itself.

something like `npm init -y package-json -- --no-prompt` should work for you.

breaking this down:

1. the `-y` is consumed by npm and avoids the prompt for installing the `create-package-json` package
2. the `--` tells npm to stop parsing arguments
3. the `--no-prompt` is passed to `create-package-json` which disables the prompting there per the docs: https://github.com/wesleytodd/create-package-json#cli-usage
