### ISSUE TITLE
running npm init with --scope is not idempotent

### ISSUE THREAD

**Issue by linclark** [npm/init-package-json#38]
If you run `npm init --scope=npm-examples` twice in the same project, it will duplicate the scope.

```
name: (@npm-examples/@npm-examples/scoped-package)
```

Can `@` be part of the project name? If not, then it seems like we could check for an `@` in the name and if it's found, split the package name and prepend the new scope.

**Comment by othiym23** [comment]
I made a change to use `npm-package-arg` to see if the package is scoped, and if so, swap out the existing scope with the new one passed via config. The behavior will be idempotent if the same scope is provided both times, otherwise it should do what most users expect.

> Can `@` be part of the project name?

Nope! But I'm trying to standardize on using `npm-package-arg` everywhere, so we have as few canonicalization functions to update when we change our minds about how all this stuff should work (which, with any luck / foresight, should happen very rarely).
